---
repos:
  - hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - args:
          - --maxkb=3000
        id: check-added-large-files
      - id: detect-private-key
      - id: check-executables-have-shebangs
      - id: check-docstring-first
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-toml
      - id: sort-simple-yaml
      - id: check-yaml
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
  - hooks:
      - args:
          - --all
        id: pycln
    repo: https://github.com/hadialqattan/pycln
    rev: v2.1.1
  - hooks:
      - id: setup-cfg-fmt
    repo: http://github.com/asottile/setup-cfg-fmt
    rev: v2.0.0
  - hooks:
      - args:
          - -iii
          - -ll
        id: bandit
    repo: https://github.com/pycqa/bandit
    rev: 1.7.4
  - hooks:
      - args:
          - --line-length=88
        id: black
    repo: https://github.com/ambv/black
    rev: 22.6.0
  - hooks:
      - additional_dependencies:
          - flake8-bugbear
          - flake8-comprehensions
          - flake8-mutable
          - flake8-print
          - flake8-simplify
        id: flake8
    repo: https://github.com/pycqa/flake8
    rev: 5.0.4
  - hooks:
      - id: mypy
    repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.971
  - hooks:
      - id: isort
    repo: https://github.com/pycqa/isort
    rev: 5.10.1
  - hooks:
      - additional_dependencies:
          - toml
        id: pydocstyle
    repo: https://github.com/pycqa/pydocstyle
    rev: 6.1.1
  - hooks:
      - args:
          - --py36-plus
          - --py37-plus
          - --py38-plus
          - --py39-plus
          - --py310-plus
        id: pyupgrade
    repo: https://github.com/asottile/pyupgrade
    rev: v2.37.3
  - hooks:
      - id: hadolint
    repo: https://github.com/AleksaC/hadolint-py
    rev: v2.10.0
  - hooks:
      - id: optimize-png
      - id: optimize-jpg
    repo: https://github.com/boidolr/pre-commit-images
    rev: v1.0.7
  - hooks:
      - id: commitizen
    repo: https://github.com/commitizen-tools/commitizen
    rev: v2.29.5
